// TOEFL 学术词汇库 · 基于 Academic Word List (AWL, Coxhead 2000, Victoria University of Wellington)
// 来源：Simple English Wiktionary "Academic word list"（完整 570 词族，按频率分 10 个 sublist）
// 说明：ETS 未发布独家完整词表；AWL 是学术界 + 托福阅读/写作公认的权威学术核心词表，覆盖约 10% 学术文本词频。
// 字段：w=headword, sl=sublist(1-10), pos=词性, zh=中文释义, en=英文释义, ex=学术例句, forms=词族
const AWL = [
// ===== Sublist 1 (60) =====
{w:"sector",sl:1,pos:"n.",zh:"部门；领域",en:"A distinct part of an economy, society, or sphere of activity.",ex:"Investment in the renewable energy sector has grown steadily.",forms:"sectors"},
{w:"available",sl:1,pos:"adj.",zh:"可获得的；可用的",en:"Able to be used or obtained; accessible.",ex:"The technology is now commercially available at low cost.",forms:"availability; unavailable"},
{w:"financial",sl:1,pos:"adj.",zh:"财政的；金融的",en:"Relating to money or finance.",ex:"The crisis revealed weaknesses in the financial system.",forms:"finances; financially"},
{w:"process",sl:1,pos:"n./v.",zh:"过程；处理",en:"A series of actions to achieve an end; to perform operations on.",ex:"The fossilization process takes thousands of years.",forms:"processes; processed; processing"},
{w:"individual",sl:1,pos:"n./adj.",zh:"个人；个体的",en:"A single human being; relating to one person.",ex:"Individual differences affect learning outcomes.",forms:"individuals; individually"},
{w:"specific",sl:1,pos:"adj.",zh:"具体的；特定的",en:"Clearly defined or identified; precise.",ex:"The grant was for a specific purpose.",forms:"specifics; specifically"},
{w:"principle",sl:1,pos:"n.",zh:"原则；原理",en:"A fundamental truth or proposition for reasoning or action.",ex:"The principle of exclusion limits competition.",forms:"principles"},
{w:"estimate",sl:1,pos:"v./n.",zh:"估计；估算",en:"To roughly calculate the value, number, or extent.",ex:"Scientists estimate millions of undiscovered species.",forms:"estimates; estimated; estimation"},
{w:"variables",sl:1,pos:"n.",zh:"变量",en:"A quantity that can change or vary.",ex:"The model controlled for several variables.",forms:"variable; variously; variance"},
{w:"method",sl:1,pos:"n.",zh:"方法；办法",en:"A particular form of procedure for accomplishing something.",ex:"Three teaching methods were compared.",forms:"methods; methodological"},
{w:"data",sl:1,pos:"n.",zh:"数据",en:"Facts and statistics collected for reference or analysis.",ex:"The data were collected over a decade.",forms:"datum"},
{w:"research",sl:1,pos:"n./v.",zh:"研究",en:"Systematic investigation to establish facts.",ex:"Decades of research show early intervention helps.",forms:"researches; researched; researcher"},
{w:"contract",sl:1,pos:"n./v.",zh:"合同；收缩",en:"A legally binding agreement; to make smaller.",ex:"The heart contracts about 100,000 times a day.",forms:"contracts; contracted; contracting"},
{w:"environment",sl:1,pos:"n.",zh:"环境",en:"The surroundings in which a person or organism lives.",ex:"Light pollution harms the urban environment.",forms:"environments; environmental"},
{w:"export",sl:1,pos:"v./n.",zh:"出口；输出",en:"To send goods to another country; a product sold abroad.",ex:"Agricultural exports earn foreign exchange.",forms:"exports; exported; exporting"},
{w:"source",sl:1,pos:"n./v.",zh:"来源；出处",en:"A place from which something comes.",ex:"Fossil fuels remain the dominant energy source.",forms:"sources; sourced"},
{w:"assessment",sl:1,pos:"n.",zh:"评估；评价",en:"The evaluation of the nature, ability, or quality of something.",ex:"Teachers use rubrics to assess writing.",forms:"assessments; assess"},
{w:"policy",sl:1,pos:"n.",zh:"政策；方针",en:"A course of action adopted by an organization or government.",ex:"Fiscal policy stabilized the financial system.",forms:"policies"},
{w:"identified",sl:1,pos:"v.",zh:"识别；确认",en:"To recognize or establish the identity of.",ex:"Sequencing can identify genetic mutations.",forms:"identify; identity; identification"},
{w:"create",sl:1,pos:"v.",zh:"创造；产生",en:"To bring something into existence.",ex:"Urbanization created new opportunities.",forms:"creates; created; creating; creation; creative"},
{w:"derived",sl:1,pos:"v.",zh:"派生；源于",en:"To obtain from a specified source.",ex:"Many drugs are derived from plants.",forms:"derive; derivation"},
{w:"factors",sl:1,pos:"n.",zh:"因素；要素",en:"A circumstance that contributes to a result.",ex:"Socioeconomic factors predict attainment.",forms:"factor"},
{w:"procedure",sl:1,pos:"n.",zh:"程序；步骤",en:"An established or official way of doing something.",ex:"All gave consent before any procedure.",forms:"procedures"},
{w:"definition",sl:1,pos:"n.",zh:"定义；释义",en:"A statement of the exact meaning of a word.",ex:"They defined what they meant by success.",forms:"definitions; define"},
{w:"assume",sl:1,pos:"v.",zh:"假定；设想",en:"To suppose to be the case without proof.",ex:"Models assume rational agents.",forms:"assumes; assumed; assuming; assumption"},
{w:"theory",sl:1,pos:"n.",zh:"理论",en:"A system of ideas to explain something.",ex:"Darwin's theory transformed biology.",forms:"theories; theoretical"},
{w:"benefit",sl:1,pos:"n./v.",zh:"益处；受益",en:"An advantage gained; to receive an advantage.",ex:"Bilingual education confers cognitive benefits.",forms:"benefits; benefited; beneficial"},
{w:"evidence",sl:1,pos:"n.",zh:"证据；迹象",en:"Facts that prove or indicate something.",ex:"It is evident from the data.",forms:"evidences; evident"},
{w:"established",sl:1,pos:"v./adj.",zh:"建立；确立",en:"To set up on a firm basis; ascertained.",ex:"Trials established the vaccine's efficacy.",forms:"establish; establishment"},
{w:"authority",sl:1,pos:"n.",zh:"权威；当局",en:"The power to give orders; an expert body.",ex:"The health authority issued guidelines.",forms:"authorities; authoritative"},
{w:"major",sl:1,pos:"adj./n.",zh:"主要的；重大",en:"Important or serious; greater in extent.",ex:"A major challenge is affordable housing.",forms:"majors; majority"},
{w:"issues",sl:1,pos:"n.",zh:"问题；议题",en:"An important topic or problem for debate.",ex:"Clean water remains a critical issue.",forms:"issue"},
{w:"labour",sl:1,pos:"n.",zh:"劳动；劳动力",en:"Work, especially physical; the workforce.",ex:"Automation reduced demand for unskilled labour.",forms:"labours; laboured"},
{w:"occur",sl:1,pos:"v.",zh:"发生；出现",en:"To happen; to be found or present.",ex:"The phenomenon occurs in equatorial regions.",forms:"occurs; occurred; occurring; occurrence"},
{w:"economic",sl:1,pos:"adj.",zh:"经济的",en:"Relating to the economy.",ex:"The shift to services altered employment.",forms:"economics; economy; economical"},
{w:"involved",sl:1,pos:"v./adj.",zh:"涉及；包含",en:"To include as a necessary element.",ex:"The process involves three reactions.",forms:"involve; involvement"},
{w:"percent",sl:1,pos:"n./adv.",zh:"百分之",en:"One part in every hundred.",ex:"A 23 percent reduction was observed.",forms:"percentage"},
{w:"interpretation",sl:1,pos:"n.",zh:"解释；解读",en:"An explanation of meaning.",ex:"Scholars interpret the text differently.",forms:"interpret; interpreting"},
{w:"consistent",sl:1,pos:"adj.",zh:"一致的",en:"Acting in the same way; compatible.",ex:"Findings were consistent across studies.",forms:"consistency; consistently"},
{w:"income",sl:1,pos:"n.",zh:"收入",en:"Money received regularly.",ex:"Childhood poverty links to lower adult income.",forms:"incomes"},
{w:"structure",sl:1,pos:"n./v.",zh:"结构；构建",en:"Arrangement of parts; to arrange systematically.",ex:"The double-helix structure was described in 1953.",forms:"structures; structural"},
{w:"legal",sl:1,pos:"adj.",zh:"法律的；合法的",en:"Based on or required by law.",ex:"The legal framework evolved.",forms:"legally; legality"},
{w:"concept",sl:1,pos:"n.",zh:"概念；观念",en:"An abstract idea or general notion.",ex:"Carrying capacity is a key concept.",forms:"concepts; conceptual"},
{w:"formula",sl:1,pos:"n.",zh:"公式；准则",en:"A mathematical rule; a fixed form.",ex:"The formula calculates compound interest.",forms:"formulas; formulae"},
{w:"section",sl:1,pos:"n./v.",zh:"部分；章节",en:"A distinct part of something.",ex:"The central section presents the framework.",forms:"sections"},
{w:"required",sl:1,pos:"v./adj.",zh:"需要；要求",en:"To need for a purpose; made necessary.",ex:"Synthesis requires coordinated action.",forms:"require; requirement"},
{w:"constitutional",sl:1,pos:"adj.",zh:"宪法的；构成的",en:"Relating to a constitution; composing.",ex:"Rights are constitutional.",forms:"constitution; constitute"},
{w:"analysis",sl:1,pos:"n.",zh:"分析",en:"Detailed examination to explain.",ex:"They analyzed data from cohorts.",forms:"analyze; analyst; analytical; analytically"},
{w:"distribution",sl:1,pos:"n.",zh:"分布；分配",en:"The act of spreading or giving out.",ex:"Aid was distributed to families.",forms:"distribute; distributive"},
{w:"function",sl:1,pos:"n./v.",zh:"功能；运作",en:"The purpose of something; to work.",ex:"The hippocampus functions in memory.",forms:"functions; functional"},
{w:"area",sl:1,pos:"n.",zh:"领域；区域",en:"A subject or range of activity; a region.",ex:"Research in this area expanded.",forms:"areas"},
{w:"approach",sl:1,pos:"n./v.",zh:"方法；接近",en:"A way of dealing with a problem.",ex:"They adopted a mixed-methods approach.",forms:"approaches; approached"},
{w:"role",sl:1,pos:"n.",zh:"角色；作用",en:"The function played in a situation.",ex:"Fungi play a crucial role.",forms:"roles"},
{w:"legislation",sl:1,pos:"n.",zh:"立法；法律",en:"Laws considered collectively.",ex:"They legislated on cybersecurity.",forms:"legislate; legislative"},
{w:"indicate",sl:1,pos:"v.",zh:"表明；指示",en:"To point out; to be a sign of.",ex:"Rising temperatures indicate change.",forms:"indicates; indicated; indicator"},
{w:"response",sl:1,pos:"n.",zh:"回应；反应",en:"A reply or reaction.",ex:"Organisms respond to stress.",forms:"respond; responsive"},
{w:"period",sl:1,pos:"n.",zh:"时期；阶段",en:"A length of time.",ex:"The Cretaceous period lasted 79 My.",forms:"periods"},
{w:"context",sl:1,pos:"n.",zh:"语境；背景",en:"The circumstances forming a setting.",ex:"Interpret within broader context.",forms:"contexts; contextual"},
{w:"significant",sl:1,pos:"adj.",zh:"显著的；重要的",en:"Worthy of attention; statistically unlikely by chance.",ex:"Results were statistically significant.",forms:"significance; significantly"},
{w:"similar",sl:1,pos:"adj.",zh:"相似的",en:"Resembling without being identical.",ex:"Similar patterns were observed.",forms:"similarity; similarly"},
// ===== Sublist 2 (60) =====
{w:"community",sl:2,pos:"n.",zh:"社区；群体",en:"A group sharing a place or characteristic.",ex:"The scientific community reached consensus.",forms:"communities; communal"},
{w:"resident",sl:2,pos:"n./adj.",zh:"居民；居住的",en:"A person living in a place.",ex:"Residents faced rising costs.",forms:"residents; residence"},
{w:"range",sl:2,pos:"n./v.",zh:"范围；变化",en:"The area between limits; to vary.",ex:"Participants ranged in age 18-74.",forms:"ranges; ranged"},
{w:"construction",sl:2,pos:"n.",zh:"建设；建造",en:"The building of something.",ex:"They constructed a new lab.",forms:"construct; constructive"},
{w:"strategies",sl:2,pos:"n.",zh:"策略；战略",en:"A plan of action to achieve a goal.",ex:"Effective strategies use spaced repetition.",forms:"strategy; strategic"},
{w:"elements",sl:2,pos:"n.",zh:"要素；元素",en:"A basic component or constituent.",ex:"Carbon is an essential element.",forms:"element; elemental"},
{w:"previous",sl:2,pos:"adj.",zh:"先前的",en:"Existing or occurring before.",ex:"Previous research found a correlation.",forms:"previously"},
{w:"conclusion",sl:2,pos:"n.",zh:"结论",en:"A judgment reached by reasoning.",ex:"The panel concluded the drug was safe.",forms:"conclude; conclusive"},
{w:"security",sl:2,pos:"n.",zh:"安全；保障",en:"The state of being safe.",ex:"They secured funding for the phase.",forms:"secure; secured"},
{w:"aspects",sl:2,pos:"n.",zh:"方面；层面",en:"A particular part or feature.",ex:"The economic aspect got less attention.",forms:"aspect"},
{w:"acquisition",sl:2,pos:"n.",zh:"获得；习得",en:"The act of getting or learning.",ex:"Children acquire language efficiently.",forms:"acquire; acquired"},
{w:"features",sl:2,pos:"n.",zh:"特征；特色",en:"A distinctive attribute.",ex:"A key feature distinguishes the model.",forms:"feature"},
{w:"text",sl:2,pos:"n.",zh:"文本；课文",en:"Written or printed work.",ex:"Academic texts use complex syntax.",forms:"texts; textual"},
{w:"commission",sl:2,pos:"n./v.",zh:"委员会；委托",en:"A group appointed for a function.",ex:"They commissioned an independent review.",forms:"commissions; commissioned"},
{w:"regulations",sl:2,pos:"n.",zh:"规章；条例",en:"Rules made by authority.",ex:"Regulations govern data privacy.",forms:"regulation; regulate"},
{w:"computer",sl:2,pos:"n.",zh:"计算机",en:"An electronic computing device.",ex:"Algorithms compute routes on computers.",forms:"computers; computing"},
{w:"items",sl:2,pos:"n.",zh:"项目；条目",en:"A distinct object or unit.",ex:"Survey respondents were divided into items.",forms:"item"},
{w:"consumer",sl:2,pos:"n.",zh:"消费者",en:"One who uses goods or services.",ex:"Developed nations consume disproportionately.",forms:"consumers; consume; consumption"},
{w:"achieve",sl:2,pos:"v.",zh:"实现；达成",en:"To accomplish through effort.",ex:"Spaced repetition helps achieve retention.",forms:"achieves; achieved; achievement"},
{w:"final",sl:2,pos:"adj.",zh:"最终的；最后的",en:"Coming at the end.",ex:"The final chapter integrates findings.",forms:"finally"},
{w:"positive",sl:2,pos:"adj.",zh:"积极的；正的",en:"Constructive; indicating presence.",ex:"Positive reinforcement is effective.",forms:"positively; positivity"},
{w:"evaluation",sl:2,pos:"n.",zh:"评估",en:"Forming a judgment of value.",ex:"Reviewers evaluated manuscripts blindly.",forms:"evaluate; evaluative"},
{w:"assistance",sl:2,pos:"n.",zh:"帮助；援助",en:"Help or support.",ex:"Tools assist researchers with datasets.",forms:"assist; assistant"},
{w:"normal",sl:2,pos:"adj.",zh:"正常的；标准的",en:"Conforming to a standard.",ex:"Values returned to normal levels.",forms:"normally; normality"},
{w:"relevant",sl:2,pos:"adj.",zh:"相关的",en:"Closely connected to the matter.",ex:"Only relevant studies were included.",forms:"relevance; irrelevant"},
{w:"distinction",sl:2,pos:"n.",zh:"区别；差别",en:"A difference or contrast.",ex:"They drew a clear distinction.",forms:"distinguish; distinct"},
{w:"region",sl:2,pos:"n.",zh:"地区；区域",en:"An area with definable traits.",ex:"Rainfall varies across the region.",forms:"regions; regional"},
{w:"traditional",sl:2,pos:"adj.",zh:"传统的",en:"Long established by tradition.",ex:"Traditional methods proved resilient.",forms:"tradition; traditionally"},
{w:"impact",sl:2,pos:"n./v.",zh:"影响；冲击",en:"A marked effect or influence.",ex:"Steam had a transformative impact.",forms:"impacts; impacted"},
{w:"consequences",sl:2,pos:"n.",zh:"后果；结果",en:"A result or effect.",ex:"The drought and its consequences hit food security.",forms:"consequence; consequent"},
{w:"chapter",sl:2,pos:"n.",zh:"章；章节",en:"A main division of a book.",ex:"The final chapter synthesizes findings.",forms:"chapters"},
{w:"equation",sl:2,pos:"n.",zh:"方程；等式",en:"A mathematical statement of equality.",ex:"The equation models the system.",forms:"equations"},
{w:"appropriate",sl:2,pos:"adj.",zh:"适当的；合适的",en:"Suitable in the circumstances.",ex:"Choosing an appropriate method is critical.",forms:"appropriately; appropriateness"},
{w:"resources",sl:2,pos:"n.",zh:"资源",en:"Assets that can be drawn on.",ex:"Developing nations face resource constraints.",forms:"resource"},
{w:"participation",sl:2,pos:"n.",zh:"参与",en:"The act of taking part.",ex:"Participation requires consent.",forms:"participate; participant"},
{w:"survey",sl:2,pos:"n./v.",zh:"调查；勘测",en:"A systematic examination.",ex:"A nationwide survey assessed habits.",forms:"surveys; surveyed"},
{w:"potential",sl:2,pos:"adj./n.",zh:"潜在的；潜力",en:"Having capacity to develop.",ex:"The technology has enormous potential.",forms:"potentially; potentiality"},
{w:"cultural",sl:2,pos:"adj.",zh:"文化的",en:"Relating to culture.",ex:"Culture shapes perception of time.",forms:"culture; culturally"},
{w:"transfer",sl:2,pos:"n./v.",zh:"转移；迁移",en:"To move from one place to another.",ex:"Learning transfer applies skills broadly.",forms:"transfers; transferred"},
{w:"select",sl:2,pos:"v.",zh:"选择；挑选",en:"To choose as most suitable.",ex:"Participants were randomly selected.",forms:"selects; selected; selection"},
{w:"credit",sl:2,pos:"n./v.",zh:"信用；归功于",en:"Recognition; to believe.",ex:"Researchers credit altered dopamine.",forms:"credits; credited"},
{w:"affect",sl:2,pos:"v.",zh:"影响",en:"To have an effect on.",ex:"Sleep deprivation affects decision-making.",forms:"affects; affected; effect"},
{w:"categories",sl:2,pos:"n.",zh:"类别；范畴",en:"A class sharing traits.",ex:"Respondents fell into income categories.",forms:"category; categorical"},
{w:"perceived",sl:2,pos:"v./adj.",zh:"感知；认为",en:"To become aware of; regarded.",ex:"People perceive color differently.",forms:"perceive; perception"},
{w:"sought",sl:2,pos:"v.",zh:"寻求",en:"Past of seek; attempted to find.",ex:"Policymakers seek evidence.",forms:"seek; seeker"},
{w:"focus",sl:2,pos:"n./v.",zh:"焦点；集中",en:"Center of interest; to pay attention.",ex:"Phase two focused on effects.",forms:"focuses; focused"},
{w:"purchase",sl:2,pos:"v./n.",zh:"购买",en:"To buy; an act of buying.",ex:"Consumers pay a premium for certs.",forms:"purchases; purchased; purchaser"},
{w:"injury",sl:2,pos:"n.",zh:"伤害；损伤",en:"Physical harm or damage.",ex:"Sedentary behavior can injure health.",forms:"injuries; injure; injured"},
{w:"site",sl:2,pos:"n.",zh:"地点；场所",en:"A place or location.",ex:"The industrial site affected residents.",forms:"sites"},
{w:"journal",sl:2,pos:"n.",zh:"期刊；日志",en:"A periodical of scholarly articles.",ex:"The finding was published in a journal.",forms:"journals"},
{w:"primary",sl:2,pos:"adj.",zh:"主要的；首要的",en:"Of chief importance.",ex:"The primary objective was quantified.",forms:"primarily"},
{w:"complex",sl:2,pos:"adj./n.",zh:"复杂的；综合体",en:"Made of many connected parts.",ex:"The framework is highly complex.",forms:"complexity; complexly"},
{w:"institute",sl:2,pos:"n./v.",zh:"机构；设立",en:"An organization for promotion; to establish.",ex:"The institute fosters interdisciplinary work.",forms:"institutes; institutional; institution"},
{w:"investment",sl:2,pos:"n.",zh:"投资",en:"The act of putting in resources.",ex:"Investment in renewables grew.",forms:"invest; investor"},
{w:"administration",sl:2,pos:"n.",zh:"管理；行政",en:"The running of an organization.",ex:"The vaccine was administered widely.",forms:"administer; administrative"},
{w:"maintenance",sl:2,pos:"n.",zh:"维护；保养",en:"The act of keeping in good state.",ex:"Maintenance costs rose.",forms:"maintain; maintained"},
{w:"design",sl:2,pos:"n./v.",zh:"设计；构思",en:"A plan showing function; to conceive.",ex:"The experimental design controlled variables.",forms:"designs; designed; designer"},
{w:"obtained",sl:2,pos:"v.",zh:"获得；取得",en:"To come to have.",ex:"Data were obtained from surveys.",forms:"obtain"},
{w:"restricted",sl:2,pos:"adj.",zh:"受限的；限制的",en:"Limited or kept under control.",ex:"They moved to restrict exports.",forms:"restrict; restriction"},
{w:"conduct",sl:2,pos:"n./v.",zh:"行为；进行",en:"Behavior; to carry out an activity.",ex:"The study was conducted over three years.",forms:"conducts; conducted; conductor"},
// ===== Sublist 3 (60) =====
{w:"comments",sl:3,pos:"n.",zh:"评论；意见",en:"A remark expressing opinion.",ex:"Reviewers commented on methods.",forms:"comment"},
{w:"convention",sl:3,pos:"n.",zh:"惯例；会议",en:"A general custom; a formal meeting.",ex:"They followed the convention.",forms:"conventions; conventional"},
{w:"published",sl:3,pos:"v./adj.",zh:"出版；发表",en:"To prepare for public distribution.",ex:"The article was published in a journal.",forms:"publish; publisher; publication"},
{w:"framework",sl:3,pos:"n.",zh:"框架；体系",en:"A basic structure underlying a concept.",ex:"The theoretical framework draws on linguistics.",forms:"frameworks"},
{w:"implies",sl:3,pos:"v.",zh:"暗示；意味着",en:"To suggest as a conclusion.",ex:"The finding implies a mechanism.",forms:"imply; implication; implied"},
{w:"negative",sl:3,pos:"adj.",zh:"负面的；否定的",en:"Lacking positive qualities; minus.",ex:"Side effects were negative.",forms:"negatively; negate"},
{w:"dominant",sl:3,pos:"adj.",zh:"主导的；支配的",en:"Most important or influential.",ex:"A few species dominate the ecosystem.",forms:"dominate; dominance"},
{w:"illustrated",sl:3,pos:"v.",zh:"阐明；图示",en:"To explain by examples or pictures.",ex:"Figure 3 illustrates the relation.",forms:"illustrate; illustration"},
{w:"outcomes",sl:3,pos:"n.",zh:"结果；后果",en:"The way a thing turns out.",ex:"The primary outcome was BP reduction.",forms:"outcome"},
{w:"constant",sl:3,pos:"adj.",zh:"持续的；恒定的",en:"Occurring continuously.",ex:"Pressure stayed constant.",forms:"constantly; constancy"},
{w:"shift",sl:3,pos:"n./v.",zh:"转变；转移",en:"A change in position or direction.",ex:"The shift to services altered work.",forms:"shifts; shifted"},
{w:"deduction",sl:3,pos:"n.",zh:"推论；扣除",en:"A conclusion by reasoning.",ex:"Geologists deduce relative ages.",forms:"deduct; deductive"},
{w:"ensure",sl:3,pos:"v.",zh:"确保；保证",en:"To make certain something happens.",ex:"QC ensures reproducibility.",forms:"ensures; ensured"},
{w:"specified",sl:3,pos:"v./adj.",zh:"明确规定",en:"To state in detail.",ex:"The grant was for a specified purpose.",forms:"specify; specification"},
{w:"justification",sl:3,pos:"n.",zh:"理由；辩护",en:"A showing of rightness.",ex:"They justified the deviation.",forms:"justify; justifiable"},
{w:"funds",sl:3,pos:"n.",zh:"资金；基金",en:"A sum set aside for a purpose.",ex:"The trial was funded by grants.",forms:"fund"},
{w:"reliance",sl:3,pos:"n.",zh:"依赖；信赖",en:"Dependence on someone or something.",ex:"Over-reliance on models is risky.",forms:"rely; reliable"},
{w:"physical",sl:3,pos:"adj.",zh:"身体的；物理的",en:"Of the body or matter.",ex:"Physical activity improves health.",forms:"physically; physics"},
{w:"partnership",sl:3,pos:"n.",zh:"合伙；合作",en:"A relationship of partners.",ex:"The university partnered with hospitals.",forms:"partner; partners"},
{w:"location",sl:3,pos:"n.",zh:"位置；地点",en:"A particular place or position.",ex:"Sites were located via imaging.",forms:"locate; located; local"},
{w:"link",sl:3,pos:"n./v.",zh:"联系；连接",en:"A relationship between things.",ex:"Research links sedentary behavior to diabetes.",forms:"links; linked"},
{w:"coordination",sl:3,pos:"n.",zh:"协调",en:"Making elements work together.",ex:"Agencies coordinated their response.",forms:"coordinate; coordinator"},
{w:"alternative",sl:3,pos:"n./adj.",zh:"替代；备选",en:"One of two or more possibilities.",ex:"They evaluated alternative approaches.",forms:"alternatives"},
{w:"initial",sl:3,pos:"adj.",zh:"最初的；开始的",en:"Existing at the beginning.",ex:"Initial findings were promising.",forms:"initially; initiate; initiation"},
{w:"validity",sl:3,pos:"n.",zh:"有效性；效度",en:"The quality of being well-founded.",ex:"The internal validity was strong.",forms:"valid; validate"},
{w:"task",sl:3,pos:"n.",zh:"任务；工作",en:"A piece of work to be done.",ex:"The task required careful design.",forms:"tasks"},
{w:"techniques",sl:3,pos:"n.",zh:"技术；技巧",en:"A way of carrying out a task.",ex:"Three techniques were compared.",forms:"technique"},
{w:"excluded",sl:3,pos:"v.",zh:"排除；不包括",en:"To leave out.",ex:"Participants with conditions were excluded.",forms:"exclude; exclusion"},
{w:"consent",sl:3,pos:"n./v.",zh:"同意；准许",en:"Permission for something.",ex:"All gave informed consent.",forms:"consensual; consensus"},
{w:"proportion",sl:3,pos:"n.",zh:"比例；部分",en:"A part relative to a whole.",ex:"A large proportion were affected.",forms:"proportions; proportional"},
{w:"demonstrate",sl:3,pos:"v.",zh:"证明；展示",en:"To show clearly by evidence.",ex:"Trials demonstrated safety.",forms:"demonstration; demonstrative"},
{w:"reaction",sl:3,pos:"n.",zh:"反应",en:"A response to stimulus.",ex:"The reaction was measured.",forms:"react; reactive"},
{w:"criteria",sl:3,pos:"n.",zh:"标准（复）",en:"Principles for judgment (plural).",ex:"Applicants met three criteria.",forms:"criterion"},
{w:"minorities",sl:3,pos:"n.",zh:"少数群体",en:"A smaller part of a population.",ex:"Outcomes varied across minorities.",forms:"minority"},
{w:"technology",sl:3,pos:"n.",zh:"技术",en:"Application of scientific knowledge.",ex:"The technology became affordable.",forms:"technical; technically"},
{w:"philosophy",sl:3,pos:"n.",zh:"哲学；理念",en:"A system of ideas.",ex:"Their philosophy values openness.",forms:"philosophical"},
{w:"removed",sl:3,pos:"v.",zh:"移除；去掉",en:"To take away.",ex:"The file was removed.",forms:"remove; removal"},
{w:"sex",sl:3,pos:"n.",zh:"性别；性",en:"Biological male/female; sexuality.",ex:"Outcomes differed by sex.",forms:"sexes; sexual"},
{w:"compensation",sl:3,pos:"n.",zh:"补偿；赔偿",en:"Something that makes up for loss.",ex:"The brain compensates for damage.",forms:"compensate; compensatory"},
{w:"sequence",sl:3,pos:"n.",zh:"序列；顺序",en:"A particular order of things.",ex:"The DNA sequence was read.",forms:"sequences; sequential"},
{w:"corresponding",sl:3,pos:"adj.",zh:"相应的；对应的",en:"Matching or equivalent.",ex:"Results correspond to predictions.",forms:"correspond; correspondence"},
{w:"maximum",sl:3,pos:"adj./n.",zh:"最大的；最大值",en:"The greatest possible.",ex:"They maximized retention.",forms:"maximize; maximal"},
{w:"circumstances",sl:3,pos:"n.",zh:"情况；环境",en:"Conditions connected with an event.",ex:"Under most circumstances, inflammation helps.",forms:"circumstance"},
{w:"instance",sl:3,pos:"n.",zh:"例子；实例",en:"A single occurrence.",ex:"There are several instances.",forms:"instances; instantiate"},
{w:"considerable",sl:3,pos:"adj.",zh:"相当大的",en:"Notably large in size.",ex:"Considerable resources were invested.",forms:"consider; considerably"},
{w:"sufficient",sl:3,pos:"adj.",zh:"充足的；足够的",en:"Enough to meet needs.",ex:"Evidence was sufficient.",forms:"sufficiency; sufficiently"},
{w:"corporate",sl:3,pos:"adj.",zh:"公司的；法人的",en:"Relating to a large company.",ex:"Corporate responsibility matters.",forms:"corporation"},
{w:"interaction",sl:3,pos:"n.",zh:"互动；相互作用",en:"Acting to affect another.",ex:"Species interact in a web.",forms:"interact; interactive"},
{w:"contribution",sl:3,pos:"n.",zh:"贡献",en:"Something given or added.",ex:"They contributed to the field.",forms:"contribute; contributor"},
{w:"immigration",sl:3,pos:"n.",zh:"移民",en:"Coming to live in a country.",ex:"Immigration reshaped cities.",forms:"immigrate; immigrant"},
{w:"component",sl:3,pos:"n.",zh:"组成部分",en:"A part of a larger whole.",ex:"Critical thinking is a component.",forms:"component"},
{w:"constraints",sl:3,pos:"n.",zh:"限制；约束",en:"Something that limits.",ex:"Resource constraints bind research.",forms:"constraint"},
{w:"technical",sl:3,pos:"adj.",zh:"技术的；专业的",en:"Relating to a specific field.",ex:"The report was technical.",forms:"technically; technique"},
{w:"emphasis",sl:3,pos:"n.",zh:"强调；重点",en:"Special importance given.",ex:"The curriculum emphasized thinking.",forms:"emphasize; emphatic"},
{w:"scheme",sl:3,pos:"n.",zh:"计划；方案",en:"A systematic plan.",ex:"The scheme was approved.",forms:"schemes"},
{w:"layer",sl:3,pos:"n./v.",zh:"层；分层",en:"A sheet or thickness.",ex:"Each sedimentary layer corresponds to a period.",forms:"layers"},
{w:"volume",sl:3,pos:"n.",zh:"体积；量；卷",en:"Amount of space; a book.",ex:"A large volume of data was generated.",forms:"volumes; volumetric"},
{w:"document",sl:3,pos:"n./v.",zh:"文件；记录",en:"Written material; to record.",ex:"They documented changes over five years.",forms:"documents; documented; documentation"},
{w:"registered",sl:3,pos:"v.",zh:"登记；注册",en:"To enter in a register.",ex:"The drug was registered.",forms:"register; registration"},
{w:"core",sl:3,pos:"n./adj.",zh:"核心；中心的",en:"The central part.",ex:"The core idea is simple.",forms:"cores"},
// ===== Sublist 4 (60) =====
{w:"overall",sl:4,pos:"adj./adv.",zh:"总体的；全面",en:"Taking everything into account.",ex:"The overall trend was clear.",forms:""},
{w:"emerged",sl:4,pos:"v.",zh:"出现；浮现",en:"To come into view or being.",ex:"New patterns emerged.",forms:"emerge; emergence"},
{w:"regime",sl:4,pos:"n.",zh:"政权；制度",en:"A system of government or rule.",ex:"The regime changed policy.",forms:"regimes"},
{w:"implementation",sl:4,pos:"n.",zh:"实施；执行",en:"Putting a plan into effect.",ex:"Implementation began in September.",forms:"implement; implemented"},
{w:"project",sl:4,pos:"n./v.",zh:"项目；规划",en:"A planned undertaking.",ex:"The project was funded.",forms:"projects; projected"},
{w:"hence",sl:4,pos:"adv.",zh:"因此；由此",en:"As a consequence.",ex:"The sample was small; hence preliminary.",forms:""},
{w:"occupational",sl:4,pos:"adj.",zh:"职业的",en:"Relating to a job or occupation.",ex:"Occupational hazards were noted.",forms:"occupation; occupy"},
{w:"internal",sl:4,pos:"adj.",zh:"内部的",en:"Situated on the inside.",ex:"An internal audit found discrepancies.",forms:"internally; intern"},
{w:"goals",sl:4,pos:"n.",zh:"目标",en:"Aims or desired results.",ex:"The primary goal was reduction.",forms:"goal"},
{w:"retained",sl:4,pos:"v.",zh:"保留；保持",en:"To keep possession of.",ex:"Water retains heat.",forms:"retain; retention"},
{w:"sum",sl:4,pos:"n.",zh:"总和；总数",en:"The total amount.",ex:"The sum of parts equals the whole.",forms:"sums; summing"},
{w:"integration",sl:4,pos:"n.",zh:"整合；集成",en:"Combining into a whole.",ex:"Integration improved flow.",forms:"integrate; integrated"},
{w:"mechanism",sl:4,pos:"n.",zh:"机制；机理",en:"A process by which something occurs.",ex:"The mechanism involves receptors.",forms:"mechanisms; mechanistic"},
{w:"parallel",sl:4,pos:"adj./n.",zh:"平行的；类似",en:"Equidistant; a similar case.",ex:"A parallel trend was seen.",forms:"parallels"},
{w:"imposed",sl:4,pos:"v.",zh:"强加；施加",en:"To force upon.",ex:"Sanctions were imposed.",forms:"impose; imposition"},
{w:"despite",sl:4,pos:"prep.",zh:"尽管；不管",en:"Without being affected by.",ex:"Despite research, the mechanism is unclear.",forms:""},
{w:"job",sl:4,pos:"n.",zh:"工作；职位",en:"Paid employment.",ex:"Automation eliminates routine jobs.",forms:"jobs"},
{w:"parameters",sl:4,pos:"n.",zh:"参数；参数",en:"A variable in a system.",ex:"The model had three parameters.",forms:"parameter"},
{w:"approximate",sl:4,pos:"adj./v.",zh:"近似的；接近",en:"Close to but not exact.",ex:"The record gives an approximate picture.",forms:"approximately; approximation"},
{w:"label",sl:4,pos:"n./v.",zh:"标签；标注",en:"A marker identifying something.",ex:"Products carry a label.",forms:"labels; labeled"},
{w:"concentration",sl:4,pos:"n.",zh:"浓度；集中",en:"The amount per volume; focus.",ex:"They concentrated on the core.",forms:"concentrate; concentric"},
{w:"principal",sl:4,pos:"adj./n.",zh:"主要的；校长",en:"Main; a school head.",ex:"The principal reason was cost.",forms:"principles; principally"},
{w:"series",sl:4,pos:"n.",zh:"系列；连续",en:"A number of similar things.",ex:"A series of trials were run.",forms:""},
{w:"predicted",sl:4,pos:"v.",zh:"预测",en:"To say what will happen.",ex:"They predicted the outcome.",forms:"predict; prediction"},
{w:"summary",sl:4,pos:"n.",zh:"摘要；总结",en:"A brief statement of main points.",ex:"The summary captured findings.",forms:"summarize; summarise"},
{w:"attitudes",sl:4,pos:"n.",zh:"态度",en:"A settled way of thinking.",ex:"Public attitudes vary.",forms:"attitude"},
{w:"undertaken",sl:4,pos:"v.",zh:"从事；承担",en:"Past of undertake; to take on.",ex:"The study was undertaken in 2020.",forms:"undertake"},
{w:"cycle",sl:4,pos:"n.",zh:"周期；循环",en:"A series of events repeating.",ex:"The cycle takes years.",forms:"cycles; cyclical"},
{w:"communication",sl:4,pos:"n.",zh:"交流；沟通",en:"The exchange of information.",ex:"Communication broke down.",forms:"communicate; communicative"},
{w:"ethnic",sl:4,pos:"adj.",zh:"民族的；种族的",en:"Relating to a cultural group.",ex:"Outcomes varied by ethnic group.",forms:"ethnicity"},
{w:"hypothesis",sl:4,pos:"n.",zh:"假设",en:"A proposed explanation.",ex:"They formulated a testable hypothesis.",forms:"hypotheses; hypothesize; hypothetical"},
{w:"professional",sl:4,pos:"adj./n.",zh:"专业的；职业的",en:"Relating to a profession.",ex:"Professional standards apply.",forms:"profession; professionally"},
{w:"status",sl:4,pos:"n.",zh:"地位；状态",en:"Relative position or condition.",ex:"The status was updated.",forms:"statuses"},
{w:"conference",sl:4,pos:"n.",zh:"会议",en:"A formal meeting.",ex:"The conference drew 500 attendees.",forms:"conferences"},
{w:"attributed",sl:4,pos:"v.",zh:"归因于",en:"To regard as caused by.",ex:"They attribute decline to habitat loss.",forms:"attribute; attribution"},
{w:"annual",sl:4,pos:"adj.",zh:"每年的",en:"Occurring once a year.",ex:"Annual emissions rose 60%.",forms:"annually"},
{w:"obvious",sl:4,pos:"adj.",zh:"明显的",en:"Easily perceived.",ex:"It is obvious from the trend.",forms:"obviously; obfuscate"},
{w:"error",sl:4,pos:"n.",zh:"错误",en:"A mistake.",ex:"Systematic errors were corrected.",forms:"errors; erroneous"},
{w:"implications",sl:4,pos:"n.",zh:"含义；暗示",en:"A likely consequence.",ex:"The implications are serious.",forms:"implication; imply"},
{w:"apparent",sl:4,pos:"adj.",zh:"明显的；表面的",en:"Clearly visible; seeming.",ex:"The apparent contradiction resolved.",forms:"apparently; apparition"},
{w:"commitment",sl:4,pos:"n.",zh:"承诺；投入",en:"A pledge or devotion.",ex:"They committed to net-zero.",forms:"commit; committed"},
{w:"subsequent",sl:4,pos:"adj.",zh:"随后的",en:"Following in time.",ex:"Subsequent analysis confirmed.",forms:"subsequently"},
{w:"debate",sl:4,pos:"n./v.",zh:"辩论；讨论",en:"A discussion of opposing views.",ex:"There is debate on the topic.",forms:"debates; debated"},
{w:"dimensions",sl:4,pos:"n.",zh:"维度；方面",en:"A measurable extent.",ex:"The problem has many dimensions.",forms:"dimension; dimensional"},
{w:"promote",sl:4,pos:"v.",zh:"促进；提升",en:"To support or advance.",ex:"Policies promote growth.",forms:"promotes; promotion"},
{w:"statistics",sl:4,pos:"n.",zh:"统计；统计学",en:"Numerical facts; a field.",ex:"Statistics show a decline.",forms:"statistical; statistically"},
{w:"option",sl:4,pos:"n.",zh:"选项；选择",en:"A thing that may be chosen.",ex:"Several options exist.",forms:"options; optional"},
{w:"domestic",sl:4,pos:"adj.",zh:"国内的；家庭的",en:"Relating to one's country.",ex:"Domestic production rose.",forms:"domestically; domesticate"},
{w:"output",sl:4,pos:"n.",zh:"产出；输出",en:"Something produced.",ex:"The output doubled.",forms:"outputs"},
{w:"access",sl:4,pos:"n./v.",zh:"获取；接近",en:"The means to approach.",ex:"Differential access persists.",forms:"accessed; accessible"},
{w:"code",sl:4,pos:"n.",zh:"代码；准则",en:"A system of symbols; rules.",ex:"The code was rewritten.",forms:"codes; coded"},
{w:"investigation",sl:4,pos:"n.",zh:"调查；研究",en:"Systematic inquiry.",ex:"A team investigated the cause.",forms:"investigate; investigative"},
{w:"phase",sl:4,pos:"n.",zh:"阶段；时期",en:"A distinct stage.",ex:"Phase two focused on effects.",forms:"phases"},
{w:"prior",sl:4,pos:"adj.",zh:"先前的；优先的",en:"Earlier in time; preceding.",ex:"Prior studies found a link.",forms:"priority; prioritize"},
{w:"granted",sl:4,pos:"v.",zh:"授予；同意",en:"To give formally.",ex:"They granted the request.",forms:"grant"},
{w:"stress",sl:4,pos:"n./v.",zh:"压力；强调",en:"Tension; to emphasize.",ex:"Stress affects health.",forms:"stresses; stressed; stressful"},
{w:"civil",sl:4,pos:"adj.",zh:"公民的；民事的",en:"Relating to citizens.",ex:"Civil rights were protected.",forms:"civically; civilian"},
{w:"contrast",sl:4,pos:"n./v.",zh:"对比；对照",en:"Difference; to compare.",ex:"The findings contrast.",forms:"contrasts; contrasted"},
{w:"resolution",sl:4,pos:"n.",zh:"决议；解决",en:"A firm decision; solving.",ex:"The resolution passed.",forms:"resolve; resolved"},
{w:"adequate",sl:4,pos:"adj.",zh:"充足的",en:"Satisfactory in quantity.",ex:"Adequate sleep is essential.",forms:"adequately; adequacy"},
// ===== Sublist 5 (60) =====
{w:"alter",sl:5,pos:"v.",zh:"改变；修改",en:"To change in character.",ex:"Practices altered the nitrogen cycle.",forms:"alters; altered; alteration"},
{w:"stability",sl:5,pos:"n.",zh:"稳定性",en:"The state of being stable.",ex:"The stability of the system held.",forms:"stable; stabilize"},
{w:"energy",sl:5,pos:"n.",zh:"能量；精力",en:"Power from resources.",ex:"Renewable energy is central.",forms:"energies; energetic"},
{w:"aware",sl:5,pos:"adj.",zh:"意识到的",en:"Having knowledge of.",ex:"Researchers were unaware.",forms:"awareness; unaware"},
{w:"licence",sl:5,pos:"n.",zh:"执照；许可",en:"Official permission.",ex:"A licence was required.",forms:"license; licensed"},
{w:"enforcement",sl:5,pos:"n.",zh:"执行；强制",en:"Compelling compliance.",ex:"Enforcement was weak.",forms:"enforce; enforced"},
{w:"draft",sl:5,pos:"n./v.",zh:"草稿；起草",en:"A preliminary version.",ex:"A draft report was circulated.",forms:"drafts; drafted"},
{w:"styles",sl:5,pos:"n.",zh:"风格；样式",en:"A manner of doing.",ex:"Writing styles differ.",forms:"style; stylistic"},
{w:"precise",sl:5,pos:"adj.",zh:"精确的",en:"Exact and accurate.",ex:"A precise measurement is key.",forms:"precisely; precision"},
{w:"medical",sl:5,pos:"adj.",zh:"医疗的",en:"Relating to medicine.",ex:"Medical advances helped.",forms:"medically; medicine"},
{w:"pursue",sl:5,pos:"v.",zh:"追求；从事",en:"To follow with intent.",ex:"They pursued the question.",forms:"pursues; pursued; pursuit"},
{w:"symbolic",sl:5,pos:"adj.",zh:"象征的",en:"Serving as a symbol.",ex:"The act was symbolic.",forms:"symbol; symbolize"},
{w:"marginal",sl:5,pos:"adj.",zh:"边缘的；微小的",en:"At the margin; small.",ex:"A marginal effect was found.",forms:"margin; marginally"},
{w:"capacity",sl:5,pos:"n.",zh:"能力；容量",en:"The ability to do; maximum hold.",ex:"They expanded capacity.",forms:"capacities; capable"},
{w:"generation",sl:5,pos:"n.",zh:"一代；产生",en:"A group born together; producing.",ex:"The next generation benefits.",forms:"generate; generated"},
{w:"exposure",sl:5,pos:"n.",zh:"暴露；接触",en:"The state of being exposed.",ex:"Exposure to light mattered.",forms:"expose; exposed"},
{w:"decline",sl:5,pos:"v./n.",zh:"下降；衰退",en:"To become smaller.",ex:"A 40% decline was documented.",forms:"declines; declined"},
{w:"academic",sl:5,pos:"adj.",zh:"学术的",en:"Relating to academia.",ex:"Academic texts are dense.",forms:"academically; academy"},
{w:"modified",sl:5,pos:"v.",zh:"修改；调整",en:"To change slightly.",ex:"The model was modified.",forms:"modify; modification"},
{w:"external",sl:5,pos:"adj.",zh:"外部的",en:"Situated outside.",ex:"External factors mattered.",forms:"externally; exterior"},
{w:"psychology",sl:5,pos:"n.",zh:"心理学",en:"The study of mind.",ex:"Psychology explains behavior.",forms:"psychological; psychologically"},
{w:"fundamental",sl:5,pos:"adj.",zh:"基本的；根本的",en:"Forming a core base.",ex:"Clean water is fundamental.",forms:"fundamentally; fundamentals"},
{w:"adjustment",sl:5,pos:"n.",zh:"调整",en:"A small change.",ex:"The model was adjusted.",forms:"adjust; adjusted"},
{w:"ratio",sl:5,pos:"n.",zh:"比率；比例",en:"Relation of two quantities.",ex:"The ratio was 3:1.",forms:"ratios"},
{w:"whereas",sl:5,pos:"conj.",zh:"然而；鉴于",en:"In contrast; while.",ex:"A rose, whereas a tulip differs.",forms:""},
{w:"enable",sl:5,pos:"v.",zh:"使能够",en:"To make possible.",ex:"Tech enabled collaboration.",forms:"enables; enabled; enabling"},
{w:"version",sl:5,pos:"n.",zh:"版本",en:"A particular form.",ex:"The latest version shipped.",forms:"versions"},
{w:"perspective",sl:5,pos:"n.",zh:"视角；观点",en:"A point of view.",ex:"From a historical perspective.",forms:"perspectives"},
{w:"contact",sl:5,pos:"n./v.",zh:"接触；联系",en:"Touching; communication.",ex:"Contact was established.",forms:"contacts; contacted"},
{w:"network",sl:5,pos:"n.",zh:"网络",en:"An interconnected system.",ex:"The network failed.",forms:"networks; networked"},
{w:"facilitate",sl:5,pos:"v.",zh:"促进；使便利",en:"To make easier.",ex:"Platforms facilitated collaboration.",forms:"facilitates; facilitation"},
{w:"welfare",sl:5,pos:"n.",zh:"福利",en:"Health and happiness.",ex:"Social welfare improved.",forms:""},
{w:"transition",sl:5,pos:"n./v.",zh:"过渡；转变",en:"A change from one state.",ex:"The transition was smooth.",forms:"transitions; transitional"},
{w:"amendment",sl:5,pos:"n.",zh:"修正；修正案",en:"A minor change to law.",ex:"Parliament amended the law.",forms:"amend; amended"},
{w:"logic",sl:5,pos:"n.",zh:"逻辑",en:"Reasoning principles.",ex:"The logic was sound.",forms:"logical; logically"},
{w:"rejected",sl:5,pos:"v.",zh:"拒绝；驳回",en:"To refuse or dismiss.",ex:"The claim was rejected.",forms:"reject; rejection"},
{w:"expansion",sl:5,pos:"n.",zh:"扩张；扩展",en:"The act of expanding.",ex:"Expansion brought growth.",forms:"expand; expanded"},
{w:"clause",sl:5,pos:"n.",zh:"条款；从句",en:"A stipulation; a grammatical unit.",ex:"An arbitration clause was included.",forms:"clauses"},
{w:"prime",sl:5,pos:"adj.",zh:"主要的；首要的",en:"Of first importance.",ex:"The prime cause was cost.",forms:"primes; primary"},
{w:"target",sl:5,pos:"n./v.",zh:"目标；瞄准",en:"An objective; to aim at.",ex:"They targeted emissions.",forms:"targets; targeted"},
{w:"objective",sl:5,pos:"adj./n.",zh:"客观的；目标",en:"Not biased; a goal.",ex:"An objective measure was used.",forms:"objectives; objectively"},
{w:"sustainable",sl:5,pos:"adj.",zh:"可持续的",en:"Able to continue long-term.",ex:"Sustainable growth matters.",forms:"sustain; sustainability"},
{w:"equivalent",sl:5,pos:"adj./n.",zh:"等价的；等同的",en:"Equal in value or function.",ex:"One credit equals three hours.",forms:"equivalence"},
{w:"liberal",sl:5,pos:"adj.",zh:"自由的；开明的",en:"Open to new ideas.",ex:"Liberal systems hold elections.",forms:"liberally; liberalism"},
{w:"notion",sl:5,pos:"n.",zh:"概念；想法",en:"A general understanding.",ex:"The notion of fairness.",forms:"notions; notionally"},
{w:"substitution",sl:5,pos:"n.",zh:"替代",en:"Replacing one with another.",ex:"Substitution changed the result.",forms:"substitute; substituted"},
{w:"generated",sl:5,pos:"v.",zh:"生成；产生",en:"To produce or create.",ex:"They generated a dataset.",forms:"generate; generation"},
{w:"trend",sl:5,pos:"n.",zh:"趋势",en:"A general direction.",ex:"The trend was upward.",forms:"trends; trended"},
{w:"revenue",sl:5,pos:"n.",zh:"收入；税收",en:"Income from sales.",ex:"Revenue rose 10%.",forms:"revenues"},
{w:"compounds",sl:5,pos:"n./v.",zh:"化合物；加重",en:"A substance of elements; to worsen.",ex:"CO2 is a compound.",forms:"compound; compounded"},
{w:"evolution",sl:5,pos:"n.",zh:"演化；进化",en:"Gradual development.",ex:"Organisms evolved.",forms:"evolve; evolved"},
{w:"conflict",sl:5,pos:"n./v.",zh:"冲突；矛盾",en:"Serious disagreement.",ex:"The findings conflict.",forms:"conflicts; conflicted"},
{w:"image",sl:5,pos:"n.",zh:"图像；形象",en:"A visual representation.",ex:"The image was clear.",forms:"images; imagery"},
{w:"discretion",sl:5,pos:"n.",zh:"谨慎；裁量",en:"Careful judgment.",ex:"At their discretion.",forms:"discretionary; discreet"},
{w:"entities",sl:5,pos:"n.",zh:"实体",en:"A distinct existence.",ex:"A state is a sovereign entity.",forms:"entity; entitle"},
{w:"orientation",sl:5,pos:"n.",zh:"方向；取向",en:"Positioning; attitude.",ex:"The orientation was clear.",forms:"orient; oriented"},
{w:"consultation",sl:5,pos:"n.",zh:"咨询；磋商",en:"Seeking advice.",ex:"Consultation preceded the draft.",forms:"consult; consultant"},
{w:"mental",sl:5,pos:"adj.",zh:"心理的；精神的",en:"Of the mind.",ex:"Mental health matters.",forms:"mentally; mentality"},
{w:"monitoring",sl:5,pos:"n.",zh:"监测；监控",en:"Observing over time.",ex:"Monitoring ensured safety.",forms:"monitor; monitored"},
{w:"challenge",sl:5,pos:"n./v.",zh:"挑战；质疑",en:"A test; to dispute.",ex:"Evidence challenged assumptions.",forms:"challenges; challenged"},
// ===== Sublist 6 (60) =====
{w:"intelligence",sl:6,pos:"n.",zh:"智力；情报",en:"The ability to learn; information.",ex:"Artificial intelligence advanced.",forms:"intelligent; intellectually"},
{w:"transformation",sl:6,pos:"n.",zh:"转变；变革",en:"A thorough change.",ex:"The transformation was complete.",forms:"transform; transformed"},
{w:"presumption",sl:6,pos:"n.",zh:"假定；推测",en:"An assumption taken as true.",ex:"The presumption was wrong.",forms:"presume; presumed"},
{w:"acknowledged",sl:6,pos:"v./adj.",zh:"承认；公认",en:"To recognize; accepted.",ex:"They acknowledged limits.",forms:"acknowledge; acknowledgment"},
{w:"utility",sl:6,pos:"n.",zh:"效用；公用事业",en:"Usefulness; public services.",ex:"The utility was sold.",forms:"utilities; utilitarian"},
{w:"furthermore",sl:6,pos:"adv.",zh:"此外；而且",en:"In addition.",ex:"The data were weak; furthermore, sparse.",forms:""},
{w:"accurate",sl:6,pos:"adj.",zh:"准确的",en:"Free from error.",ex:"Accurate measurement is essential.",forms:"accurately; accuracy"},
{w:"diversity",sl:6,pos:"n.",zh:"多样性",en:"The state of being varied.",ex:"Linguistic diversity matters.",forms:"diverse; diversify"},
{w:"attached",sl:6,pos:"v.",zh:"附上；连接",en:"To fasten or connect.",ex:"Cells attach to the matrix.",forms:"attach; attachment"},
{w:"recovery",sl:6,pos:"n.",zh:"恢复；复苏",en:"A return to normal.",ex:"Recovery took years.",forms:"recover; recovered"},
{w:"assigned",sl:6,pos:"v.",zh:"分配；指派",en:"To allocate a task.",ex:"They were assigned to groups.",forms:"assign; assignment"},
{w:"tapes",sl:6,pos:"n.",zh:"磁带；胶带",en:"A recording medium.",ex:"The tapes were archived.",forms:"tape"},
{w:"motivation",sl:6,pos:"n.",zh:"动机；动力",en:"The reason to act.",ex:"Intrinsic motivation drives learning.",forms:"motivate; motivated"},
{w:"bond",sl:6,pos:"n./v.",zh:"键；结合",en:"A force joining; to connect.",ex:"Covalent bonds are strong.",forms:"bonds; bonded"},
{w:"edition",sl:6,pos:"n.",zh:"版本；版次",en:"A particular form of publication.",ex:"The second edition shipped.",forms:"editions; edit"},
{w:"nevertheless",sl:6,pos:"adv.",zh:"然而；不过",en:"In spite of that.",ex:"Weak; nevertheless published.",forms:""},
{w:"transport",sl:6,pos:"n./v.",zh:"运输；交通",en:"Moving goods or people.",ex:"Transport emitted CO2.",forms:"transports; transported; transportation"},
{w:"cited",sl:6,pos:"v.",zh:"引用",en:"To quote as evidence.",ex:"The study cited 150 papers.",forms:"cite; citation"},
{w:"fees",sl:6,pos:"n.",zh:"费用",en:"A payment for service.",ex:"The fees rose.",forms:"fee"},
{w:"scope",sl:6,pos:"n.",zh:"范围；广度",en:"The extent of coverage.",ex:"The scope was broad.",forms:"scopes"},
{w:"enhanced",sl:6,pos:"v./adj.",zh:"增强；提升",en:"To improve quality.",ex:"Fertilizer enhanced yields.",forms:"enhance; enhancement"},
{w:"incorporated",sl:6,pos:"v.",zh:"合并；纳入",en:"To include as part.",ex:"They incorporated feedback.",forms:"incorporate; incorporation"},
{w:"instructions",sl:6,pos:"n.",zh:"指令；说明",en:"Directions for doing.",ex:"Follow the instructions.",forms:"instruct; instruction"},
{w:"subsidiary",sl:6,pos:"n./adj.",zh:"子公司；附属的",en:"A subordinate company.",ex:"The subsidiary was sold.",forms:"subsidiaries; subsidize"},
{w:"input",sl:6,pos:"n.",zh:"输入；投入",en:"What is put in.",ex:"User input shaped the design.",forms:"inputs"},
{w:"abstract",sl:6,pos:"adj./n.",zh:"抽象的；摘要",en:"Thought not concrete; a summary.",ex:"The abstract was brief.",forms:"abstracts; abstraction"},
{w:"ministry",sl:6,pos:"n.",zh:"部委；部",en:"A government department.",ex:"The ministry issued rules.",forms:"minister; ministerial"},
{w:"capable",sl:6,pos:"adj.",zh:"有能力的",en:"Having the ability.",ex:"Systems are capable of reading genomes.",forms:"capability; incapabable"},
{w:"expert",sl:6,pos:"n./adj.",zh:"专家；专业的",en:"A skilled person.",ex:"An expert reviewed it.",forms:"experts; expertise"},
{w:"preceding",sl:6,pos:"adj.",zh:"前面的；先前的",en:"Coming before.",ex:"The preceding section set context.",forms:"precede; precedent"},
{w:"display",sl:6,pos:"v./n.",zh:"展示；显示",en:"To show.",ex:"Neurons display patterns.",forms:"displays; displayed"},
{w:"incentive",sl:6,pos:"n.",zh:"激励；诱因",en:"Something motivating.",ex:"Incentives improved uptake.",forms:"incentives"},
{w:"inhibition",sl:6,pos:"n.",zh:"抑制；禁止",en:"The act of holding back.",ex:"Inhibition reduced noise.",forms:"inhibit; inhibited"},
{w:"trace",sl:6,pos:"n./v.",zh:"痕迹；追踪",en:"A small sign; to follow.",ex:"Sensors trace contaminants.",forms:"traces; traced"},
{w:"ignored",sl:6,pos:"v.",zh:"忽视",en:"To pay no attention.",ex:"The warning was ignored.",forms:"ignore; ignorance"},
{w:"incidence",sl:6,pos:"n.",zh:"发生率；入射",en:"The rate of occurrence.",ex:"Incidence rose.",forms:"incident; incidental"},
{w:"estate",sl:6,pos:"n.",zh:"地产；财产",en:"A piece of property.",ex:"The estate was large.",forms:"estates"},
{w:"cooperative",sl:6,pos:"adj./n.",zh:"合作的；合作社",en:"Willing to work together.",ex:"A cooperative approach helped.",forms:"cooperate; cooperation"},
{w:"revealed",sl:6,pos:"v.",zh:"揭示；显露",en:"To make known.",ex:"Data revealed three patterns.",forms:"reveal; revelation"},
{w:"index",sl:6,pos:"n.",zh:"指数；索引",en:"A pointer; a measure.",ex:"The index rose.",forms:"indices; indexed"},
{w:"lecture",sl:6,pos:"n./v.",zh:"讲座；讲课",en:"A formal talk.",ex:"The lecture covered methods.",forms:"lectures; lectured"},
{w:"discrimination",sl:6,pos:"n.",zh:"歧视；辨别",en:"Unfair distinction; discernment.",ex:"The law forbids discrimination.",forms:"discriminate; discriminatory"},
{w:"overseas",sl:6,pos:"adv./adj.",zh:"海外",en:"Across the sea; abroad.",ex:"Overseas sales grew.",forms:""},
{w:"explicit",sl:6,pos:"adj.",zh:"明确的",en:"Stated clearly.",ex:"Explicit instructions were given.",forms:"explicitly; explicitness"},
{w:"aggregate",sl:6,pos:"adj./n./v.",zh:"总计的；合计",en:"Combined into a whole.",ex:"Aggregate demand fell.",forms:"aggregates; aggregated"},
{w:"gender",sl:6,pos:"n.",zh:"性别",en:"Social sex category.",ex:"Gender gaps persist.",forms:"genders"},
{w:"underlying",sl:6,pos:"adj.",zh:"潜在的；根本的",en:"Beneath the surface.",ex:"The underlying cause was cost.",forms:"underlie; underlay"},
{w:"brief",sl:6,pos:"adj.",zh:"简短的",en:"Of short duration.",ex:"A brief overview was given.",forms:"briefly; brevity"},
{w:"domain",sl:6,pos:"n.",zh:"领域；范围",en:"A sphere of knowledge.",ex:"Expertise in one domain.",forms:"domains"},
{w:"rational",sl:6,pos:"adj.",zh:"理性的；合理的",en:"Based on reason.",ex:"Rational actors maximize utility.",forms:"rationally; rationale"},
{w:"minimum",sl:6,pos:"adj./n.",zh:"最小的；最小值",en:"The least possible.",ex:"Minimize the impact.",forms:"minimize; minimal"},
{w:"interval",sl:6,pos:"n.",zh:"间隔；区间",en:"A gap in time or space.",ex:"At intervals they measured.",forms:"intervals"},
{w:"neutral",sl:6,pos:"adj.",zh:"中立的；中性的",en:"Not taking sides.",ex:"A neutral stance was taken.",forms:"neutrally; neutrality"},
{w:"migration",sl:6,pos:"n.",zh:"迁移；移居",en:"Moving to a new place.",ex:"Migration reshaped cities.",forms:"migrate; migrated"},
{w:"flexibility",sl:6,pos:"n.",zh:"灵活性",en:"Ability to adapt.",ex:"A flexible framework helps.",forms:"flexible; flexibly"},
{w:"federal",sl:6,pos:"adj.",zh:"联邦的",en:"Relating to a federation.",ex:"Federal grants funded it.",forms:"federation; federally"},
{w:"author",sl:6,pos:"n./v.",zh:"作者；创作",en:"A writer; to originate.",ex:"The article was authored by a team.",forms:"authors; authority; authorized"},
{w:"initiatives",sl:6,pos:"n.",zh:"倡议；主动",en:"A new plan or action.",ex:"New initiatives launched.",forms:"initiative; initial"},
{w:"allocation",sl:6,pos:"n.",zh:"分配",en:"Distributing for a purpose.",ex:"Allocation of funds was debated.",forms:"allocate; allocated"},
{w:"exceed",sl:6,pos:"v.",zh:"超过；超出",en:"To go beyond.",ex:"Costs exceeded budget.",forms:"exceeds; exceeded; exceeding"},
// ===== Sublist 7 (60) =====
{w:"intervention",sl:7,pos:"n.",zh:"干预；介入",en:"Action to improve a result.",ex:"The intervention helped.",forms:"intervene; intervened"},
{w:"confirmed",sl:7,pos:"v.",zh:"确认",en:"To establish as true.",ex:"They confirmed the finding.",forms:"confirm; confirmation"},
{w:"definite",sl:7,pos:"adj.",zh:"明确的；肯定的",en:"Clear and certain.",ex:"No definite cure exists.",forms:"definitely; definition"},
{w:"classical",sl:7,pos:"adj.",zh:"经典的；古典的",en:"Of highest standard.",ex:"Classical theory assumes perfect info.",forms:"classic; classics"},
{w:"chemical",sl:7,pos:"adj./n.",zh:"化学的；化学品",en:"Relating to chemistry.",ex:"Chemical pollutants persist.",forms:"chemicals; chemically"},
{w:"voluntary",sl:7,pos:"adj.",zh:"自愿的",en:"Done by choice.",ex:"Voluntary compliance rose.",forms:"volunteer; voluntarily"},
{w:"release",sl:7,pos:"n./v.",zh:"释放；发布",en:"To set free.",ex:"They released the data.",forms:"releases; released"},
{w:"visible",sl:7,pos:"adj.",zh:"可见的",en:"Able to be seen.",ex:"The effect was visible.",forms:"vision; visibly"},
{w:"finite",sl:7,pos:"adj.",zh:"有限的",en:"Having an end.",ex:"Reserves are finite.",forms:"finitely; infinity"},
{w:"publication",sl:7,pos:"n.",zh:"出版；出版物",en:"The act of publishing.",ex:"Publication followed review.",forms:"publish; published"},
{w:"channel",sl:7,pos:"n./v.",zh:"渠道；引导",en:"A means of communication.",ex:"Social media channels spread info.",forms:"channels; channelled"},
{w:"file",sl:7,pos:"n./v.",zh:"文件；归档",en:"A collection of data.",ex:"The file was stored.",forms:"files; filed"},
{w:"thesis",sl:7,pos:"n.",zh:"论文；论点",en:"A research paper; a claim.",ex:"The thesis argued X.",forms:"theses"},
{w:"equipment",sl:7,pos:"n.",zh:"设备；器材",en:"Tools for a purpose.",ex:"The lab lacked equipment.",forms:"equip; equipped"},
{w:"disposal",sl:7,pos:"n.",zh:"处理；处置",en:"Getting rid of.",ex:"Waste disposal mattered.",forms:"dispose; disposed"},
{w:"solely",sl:7,pos:"adv.",zh:"仅仅；唯一",en:"Only.",ex:"Funded solely by grants.",forms:"sole; solitary"},
{w:"deny",sl:7,pos:"v.",zh:"否认；拒绝",en:"To refuse to admit.",ex:"It is hard to deny.",forms:"denies; denied; denial"},
{w:"identical",sl:7,pos:"adj.",zh:"相同的",en:"Exactly alike.",ex:"Identical twins share DNA.",forms:"identity; identically"},
{w:"submitted",sl:7,pos:"v.",zh:"提交",en:"To present for review.",ex:"They submitted the paper.",forms:"submit; submission"},
{w:"grade",sl:7,pos:"n./v.",zh:"等级；评分",en:"A level; to assess.",ex:"Specimens were graded.",forms:"grades; graded"},
{w:"phenomenon",sl:7,pos:"n.",zh:"现象",en:"An observable fact.",ex:"The phenomenon was rare.",forms:"phenomena"},
{w:"paradigm",sl:7,pos:"n.",zh:"范式；模式",en:"A model or framework.",ex:"The dominant paradigm shifted.",forms:"paradigms; paradigmatic"},
{w:"ultimately",sl:7,pos:"adv.",zh:"最终",en:"In the end.",ex:"Ultimately, cost decides.",forms:"ultimate; ultimatum"},
{w:"extract",sl:7,pos:"n./v.",zh:"提取；摘录",en:"To remove; a passage.",ex:"They extracted DNA.",forms:"extracts; extracted; extraction"},
{w:"survive",sl:7,pos:"v.",zh:"生存；存活",en:"To continue living.",ex:"Few species survive.",forms:"survives; survival"},
{w:"converted",sl:7,pos:"v.",zh:"转换；转化",en:"To change form.",ex:"Plants convert energy.",forms:"convert; conversion"},
{w:"transmission",sl:7,pos:"n.",zh:"传输；传播",en:"Sending across.",ex:"Transmission was efficient.",forms:"transmit; transmitted"},
{w:"global",sl:7,pos:"adj.",zh:"全球的",en:"Worldwide.",ex:"Global temperatures rose.",forms:"globe; globally"},
{w:"inferred",sl:7,pos:"v.",zh:"推断",en:"To conclude by reasoning.",ex:"They inferred the source.",forms:"infer; inference"},
{w:"guarantee",sl:7,pos:"n./v.",zh:"保证；担保",en:"A formal assurance.",ex:"No study guarantees success.",forms:"guarantees; guaranteed"},
{w:"advocate",sl:7,pos:"v./n.",zh:"提倡；倡导者",en:"To support; a supporter.",ex:"They advocate investment.",forms:"advocates; advocacy"},
{w:"dynamic",sl:7,pos:"adj./n.",zh:"动态的；动力",en:"Constantly changing.",ex:"A dynamic relationship.",forms:"dynamics; dynamically"},
{w:"simulation",sl:7,pos:"n.",zh:"模拟；仿真",en:"Imitating a system.",ex:"The simulation matched data.",forms:"simulate; simulated"},
{w:"topic",sl:7,pos:"n.",zh:"话题；主题",en:"A subject of discussion.",ex:"The topic was controversial.",forms:"topics; topical"},
{w:"insert",sl:7,pos:"n./v.",zh:"插入；嵌入",en:"To place into.",ex:"They inserted a gene.",forms:"inserts; inserted; insertion"},
{w:"reverse",sl:7,pos:"adj./v.",zh:"相反的；逆转",en:"Opposite; to turn back.",ex:"The reverse trend appeared.",forms:"reverses; reversed; reversal"},
{w:"decades",sl:7,pos:"n.",zh:"数十年",en:"Periods of ten years.",ex:"Over three decades, costs fell.",forms:"decade"},
{w:"comprise",sl:7,pos:"v.",zh:"包含；构成",en:"To consist of.",ex:"The whole comprises parts.",forms:"comprises; comprised; comprehensive"},
{w:"hierarchical",sl:7,pos:"adj.",zh:"等级的；层级的",en:"Ranked by status.",ex:"A hierarchical system.",forms:"hierarchy; hierarchically"},
{w:"unique",sl:7,pos:"adj.",zh:"独特的",en:"Being the only one.",ex:"A unique solution exists.",forms:"uniquely; uniqueness"},
{w:"comprehensive",sl:7,pos:"adj.",zh:"全面的",en:"Covering fully.",ex:"A comprehensive review.",forms:"comprehend; comprehension"},
{w:"couple",sl:7,pos:"n./v.",zh:"一对；结合",en:"Two; to combine.",ex:"High inflation coupled with slow growth.",forms:"couples; coupled"},
{w:"mode",sl:7,pos:"n.",zh:"模式；方式",en:"A way of doing.",ex:"The mode of transport.",forms:"modes; modal"},
{w:"differentiation",sl:7,pos:"n.",zh:"区分；分化",en:"Recognizing differences.",ex:"Differentiate cause from effect.",forms:"differentiate; different"},
{w:"eliminate",sl:7,pos:"v.",zh:"消除；排除",en:"To remove fully.",ex:"No intervention eliminates all risk.",forms:"eliminates; elimination"},
{w:"priority",sl:7,pos:"n.",zh:"优先；重点",en:"Something ranked first.",ex:"A top priority.",forms:"priorities; prioritize"},
{w:"empirical",sl:7,pos:"adj.",zh:"经验的；实证的",en:"Based on observation.",ex:"Empirical evidence supports it.",forms:"empirically; empiricism"},
{w:"ideology",sl:7,pos:"n.",zh:"意识形态",en:"A system of ideas.",ex:"Competing ideologies clashed.",forms:"ideological; ideologically"},
{w:"somewhat",sl:7,pos:"adv.",zh:"有点；稍微",en:"To some degree.",ex:"Somewhat unclear.",forms:""},
{w:"aid",sl:7,pos:"n./v.",zh:"援助；帮助",en:"Help or support.",ex:"Aid aligned with priorities.",forms:"aids; aided"},
{w:"foundation",sl:7,pos:"n.",zh:"基础；基金会",en:"A base; an institution.",ex:"The theory is well-founded.",forms:"found; founded"},
{w:"adults",sl:7,pos:"n.",zh:"成人",en:"Mature individuals.",ex:"Adult learners differ.",forms:"adult"},
{w:"adaptation",sl:7,pos:"n.",zh:"适应；改编",en:"Adjusting to conditions.",ex:"Species adapt or die.",forms:"adapt; adapted"},
{w:"quotation",sl:7,pos:"n.",zh:"引文；报价",en:"A cited passage.",ex:"A quotation opened the chapter.",forms:"quote; quoted"},
{w:"contrary",sl:7,pos:"adj./n.",zh:"相反的",en:"Opposite in nature.",ex:"On the contrary, it rose.",forms:"contrast; contrarily"},
{w:"media",sl:7,pos:"n.",zh:"媒体；媒介",en:"Means of communication.",ex:"The media reported it.",forms:"medium; medial"},
{w:"successive",sl:7,pos:"adj.",zh:"连续的",en:"Following in sequence.",ex:"Successive trials failed.",forms:"success; succeed"},
{w:"innovation",sl:7,pos:"n.",zh:"创新",en:"A new method or idea.",ex:"Innovation drives advantage.",forms:"innovate; innovative"},
{w:"prohibited",sl:7,pos:"v./adj.",zh:"禁止",en:"Not allowed.",ex:"The drug is prohibited.",forms:"prohibit; prohibition"},
{w:"isolated",sl:7,pos:"adj.",zh:"孤立的；隔离的",en:"Separated from others.",ex:"An isolated case.",forms:"isolate; isolation"},
// ===== Sublist 8 (60) =====
{w:"highlighted",sl:8,pos:"v.",zh:"突出；强调",en:"To emphasize.",ex:"They highlighted the risk.",forms:"highlight; highlighting"},
{w:"eventually",sl:8,pos:"adv.",zh:"最终",en:"At some later time.",ex:"It eventually became affordable.",forms:"event; eventual"},
{w:"inspection",sl:8,pos:"n.",zh:"检查；视察",en:"Critical examination.",ex:"Sites are inspected annually.",forms:"inspect; inspected"},
{w:"termination",sl:8,pos:"n.",zh:"终止；结束",en:"The end of something.",ex:"Termination ended the contract.",forms:"terminate; terminated"},
{w:"displacement",sl:8,pos:"n.",zh:"位移；取代",en:"Moving from place.",ex:"Automation displaced workers.",forms:"displace; displaced"},
{w:"arbitrary",sl:8,pos:"adj.",zh:"任意的；武断的",en:"Based on whim.",ex:"Boundaries are arbitrary.",forms:"arbitrarily; arbitrariness"},
{w:"reinforced",sl:8,pos:"v.",zh:"加强；加固",en:"To strengthen.",ex:"They reinforced the finding.",forms:"reinforce; reinforcement"},
{w:"denote",sl:8,pos:"v.",zh:"表示；意指",en:"To be a sign of.",ex:"An asterisk denotes significance.",forms:"denotation; denotative"},
{w:"offset",sl:8,pos:"n./v.",zh:"抵消；补偿",en:"To counterbalance.",ex:"Gains offset losses.",forms:"offsets; offsetted"},
{w:"exploitation",sl:8,pos:"n.",zh:"开发；剥削",en:"Using resources; unfair use.",ex:"Exploitation exceeded replenishment.",forms:"exploit; exploited"},
{w:"detected",sl:8,pos:"v.",zh:"检测；发现",en:"To discover presence.",ex:"Sensors detect contaminants.",forms:"detect; detection"},
{w:"abandon",sl:8,pos:"v.",zh:"放弃；抛弃",en:"To give up.",ex:"They abandoned the hypothesis.",forms:"abandons; abandoned; abandonment"},
{w:"random",sl:8,pos:"adj.",zh:"随机的",en:"By chance.",ex:"Randomly selected.",forms:"randomly; randomness"},
{w:"revision",sl:8,pos:"n.",zh:"修订；复习",en:"A revised version.",ex:"A revision improved clarity.",forms:"revise; revised"},
{w:"virtually",sl:8,pos:"adv.",zh:"几乎；实际上",en:"Nearly; in effect.",ex:"Virtually unchanged.",forms:"virtual; virtue"},
{w:"uniform",sl:8,pos:"adj.",zh:"统一的；一致的",en:"Not varying.",ex:"Uniform standards applied.",forms:"uniformly; uniformity"},
{w:"predominantly",sl:8,pos:"adv.",zh:"主要地",en:"Mostly.",ex:"Predominantly rural.",forms:"predominant; predominate"},
{w:"thereby",sl:8,pos:"adv.",zh:"因此；从而",en:"By that means.",ex:"They optimized, thereby saving.",forms:""},
{w:"implicit",sl:8,pos:"adj.",zh:"隐含的；含蓄的",en:"Implied not stated.",ex:"The model rests on implicit assumptions.",forms:"implicitly; imply"},
{w:"tension",sl:8,pos:"n.",zh:"张力；紧张",en:"Pulling force; strain.",ex:"Tension rose.",forms:"tensile; tense"},
{w:"ambiguous",sl:8,pos:"adj.",zh:"模糊的；歧义的",en:"Open to interpretation.",ex:"The results were ambiguous.",forms:"ambiguously; ambiguity"},
{w:"vehicle",sl:8,pos:"n.",zh:"车辆；载体",en:"A means of transport.",ex:"The vehicle was electric.",forms:"vehicles"},
{w:"clarity",sl:8,pos:"n.",zh:"清晰；明了",en:"The state of being clear.",ex:"Clarity improved comprehension.",forms:"clear; clarify"},
{w:"conformity",sl:8,pos:"n.",zh:" conform; 一致",en:"Compliance with standards.",ex:"Conformity was required.",forms:"conform; conformable"},
{w:"contemporary",sl:8,pos:"adj.",zh:"当代的；同时代的",en:"Modern; of the same time.",ex:"Contemporary scholarship.",forms:"contemporarily; contemporaneous"},
{w:"automatically",sl:8,pos:"adv.",zh:"自动地",en:"By itself.",ex:"Runs automatically.",forms:"automatic; automate"},
{w:"accumulation",sl:8,pos:"n.",zh:"积累；积聚",en:"Gathering over time.",ex:"Pollutants accumulate.",forms:"accumulate; accumulated"},
{w:"appendix",sl:8,pos:"n.",zh:"附录；阑尾",en:"Supplementary material.",ex:"Data are in the appendix.",forms:"appendices; appendage"},
{w:"widespread",sl:8,pos:"adj.",zh:"广泛的",en:"Over a wide area.",ex:"Widespread adoption.",forms:""},
{w:"infrastructure",sl:8,pos:"n.",zh:"基础设施",en:"Basic physical systems.",ex:"Investment in infrastructure.",forms:"infrastructural; infrastructured"},
{w:"deviation",sl:8,pos:"n.",zh:"偏离；偏差",en:"Departure from norm.",ex:"Deviation was reported.",forms:"deviate; deviated"},
{w:"fluctuations",sl:8,pos:"n.",zh:"波动；起伏",en:"Irregular changes.",ex:"Yields fluctuate yearly.",forms:"fluctuate; fluctuated"},
{w:"restore",sl:8,pos:"v.",zh:"恢复；修复",en:"To bring back.",ex:"They restored the site.",forms:"restores; restored; restoration"},
{w:"guidelines",sl:8,pos:"n.",zh:"指南；准则",en:"Recommended practices.",ex:"Follow the guidelines.",forms:"guideline; guide"},
{w:"commodity",sl:8,pos:"n.",zh:"商品",en:"A traded good.",ex:"Oil is a commodity.",forms:"commodities"},
{w:"minimises",sl:8,pos:"v.",zh:"最小化",en:"British spelling of minimize.",ex:"It minimises risk.",forms:"minimise; minimal"},
{w:"practitioners",sl:8,pos:"n.",zh:"从业者； practitioners",en:"A person practicing a profession.",ex:"Practitioners reported gains.",forms:"practitioner; practise"},
{w:"radical",sl:8,pos:"adj.",zh:"激进的；根本的",en:"Far-reaching.",ex:"A radical change.",forms:"radically; radicle"},
{w:"plus",sl:8,pos:"prep./conj.",zh:"加；而且",en:"Added to; moreover.",ex:"Cost plus risk.",forms:""},
{w:"visual",sl:8,pos:"adj.",zh:"视觉的",en:"Of sight.",ex:"Visual aids helped.",forms:"visually; vision"},
{w:"chart",sl:8,pos:"n./v.",zh:"图表；绘制",en:"A data display.",ex:"Figure 2 charts decline.",forms:"charts; charted"},
{w:"appreciation",sl:8,pos:"n.",zh:"欣赏；增值",en:"Recognition of worth.",ex:"They appreciate the extent.",forms:"appreciate; appreciated"},
{w:"prospect",sl:8,pos:"n.",zh:"前景；期望",en:"Likelihood; a view.",ex:"The prospect improved.",forms:"prospects; prospective"},
{w:"dramatic",sl:8,pos:"adj.",zh:"戏剧性的；显著的",en:"Striking; sudden.",ex:"A dramatic impact.",forms:"dramatically; drama"},
{w:"contradiction",sl:8,pos:"n.",zh:"矛盾；反驳",en:"Conflict with.",ex:"The finding contradicts.",forms:"contradict; contradictory"},
{w:"currency",sl:8,pos:"n.",zh:"货币；流通",en:"Money in use.",ex:"The currency of an idea.",forms:"current; currently"},
{w:"inevitably",sl:8,pos:"adv.",zh:"不可避免地",en:"Certain to happen.",ex:"Growth inevitably pressures resources.",forms:"inevitable; inevitability"},
{w:"complement",sl:8,pos:"n./v.",zh:"补充；补足",en:"Something completing.",ex:"Interviews complement surveys.",forms:"complements; complementary"},
{w:"accompany",sl:8,pos:"v.",zh:"伴随；陪同",en:"To go with.",ex:"Growth accompanied urbanization.",forms:"accompanies; accompanied; company"},
{w:"paragraph",sl:8,pos:"n.",zh:"段落",en:"A section of text.",ex:"The paragraph was clear.",forms:"paragraphs"},
{w:"induced",sl:8,pos:"v.",zh:"诱发；引起",en:"To cause.",ex:"Heat induces changes.",forms:"induce; induction"},
{w:"schedule",sl:8,pos:"n./v.",zh:"日程；安排",en:"A plan of times.",ex:"The schedule slipped.",forms:"schedules; scheduled"},
{w:"intensity",sl:8,pos:"n.",zh:"强度",en:"The degree of force.",ex:"Intensity varied.",forms:"intense; intensify"},
{w:"crucial",sl:8,pos:"adj.",zh:"关键的；至关重要的",en:"Decisive important.",ex:"A crucial step.",forms:"crucially; crux"},
{w:"via",sl:8,pos:"prep.",zh:"经由；通过",en:"By way of.",ex:"Sent via email.",forms:""},
{w:"exhibit",sl:8,pos:"v./n.",zh:"展示；展览",en:"To display.",ex:"Organisms exhibit resistance.",forms:"exhibits; exhibited; exhibition"},
{w:"bias",sl:8,pos:"n./v.",zh:"偏见；偏向",en:"Unfair preference.",ex:"Confirmation bias misleads.",forms:"biases; biased"},
{w:"manipulation",sl:8,pos:"n.",zh:"操纵；处理",en:"Skillful control.",ex:"The variable was manipulated.",forms:"manipulate; manipulated"},
{w:"theme",sl:8,pos:"n.",zh:"主题；主题",en:"A subject or topic.",ex:"The theme was clear.",forms:"themes; thematic"},
{w:"nuclear",sl:8,pos:"adj.",zh:"核的",en:"Of the nucleus or atom.",ex:"Nuclear power emits no CO2.",forms:"nuclei; nucleate"},
// ===== Sublist 9 (60) =====
{w:"bulk",sl:9,pos:"n.",zh:"大部分；体积",en:"The greater part.",ex:"The bulk of variation.",forms:"bulks; bulky"},
{w:"behalf",sl:9,pos:"n.",zh:"代表；利益",en:"In the interest of.",ex:"On behalf of the coalition.",forms:""},
{w:"unified",sl:9,pos:"v./adj.",zh:"统一；联合",en:"Made into one.",ex:"A unified model.",forms:"unify; uniform"},
{w:"commenced",sl:9,pos:"v.",zh:"开始",en:"Past of commence; began.",ex:"They commenced the trial.",forms:"commence; commencement"},
{w:"erosion",sl:9,pos:"n.",zh:"侵蚀；削弱",en:"Gradual wearing away.",ex:"Trust eroded.",forms:"erode; eroded"},
{w:"anticipated",sl:9,pos:"v.",zh:"预期；预料",en:"To expect.",ex:"They did not anticipate the effect.",forms:"anticipate; anticipation"},
{w:"minimal",sl:9,pos:"adj.",zh:"最小的",en:"Least possible.",ex:"Minimal side effects.",forms:"minimize; minimum"},
{w:"ceases",sl:9,pos:"v.",zh:"停止；终止",en:"To come to an end.",ex:"Subsidies should cease.",forms:"cease; ceased"},
{w:"vision",sl:9,pos:"n.",zh:"愿景；视力",en:"Sight; imagination.",ex:"A clear vision.",forms:"visions; visible"},
{w:"mutual",sl:9,pos:"adj.",zh:"相互的",en:"Shared by two.",ex:"Mutual benefit.",forms:"mutually; mutate"},
{w:"norms",sl:9,pos:"n.",zh:"规范；标准",en:"Standards of behavior.",ex:"Social norms shifted.",forms:"norm; normal"},
{w:"intermediate",sl:9,pos:"adj.",zh:"中间的",en:"Between two extremes.",ex:"An intermediate stage.",forms:"intermediately; intermission"},
{w:"manual",sl:9,pos:"adj./n.",zh:"手动的；手册",en:"By hand; a guide.",ex:"Manual control.",forms:"manually; manipulate"},
{w:"supplementary",sl:9,pos:"adj.",zh:"补充的",en:"Adding to complete.",ex:"Supplementary material.",forms:"supplement; supplemented"},
{w:"incompatible",sl:9,pos:"adj.",zh:"不兼容的",en:"Not able to coexist.",ex:"The two are incompatible.",forms:"compatibly; compatibility"},
{w:"concurrent",sl:9,pos:"adj.",zh:"同时的",en:"Happening together.",ex:"Concurrent decline.",forms:"concurrency; concurrently"},
{w:"ethical",sl:9,pos:"adj.",zh:"伦理的；道德的",en:"Of ethics.",ex:"Ethical guidelines apply.",forms:"ethically; ethics"},
{w:"preliminary",sl:9,pos:"adj.",zh:"初步的",en:"Introductory.",ex:"Preliminary findings.",forms:"preliminarily; prelude"},
{w:"integral",sl:9,pos:"adj.",zh:"完整的；必需的",en:"Essential part.",ex:"Integrity is integral.",forms:"integrate; integrity"},
{w:"conversely",sl:9,pos:"adv.",zh:"相反地",en:"In the opposite way.",ex:"Conversely, it fell.",forms:"converse; conversion"},
{w:"relaxed",sl:9,pos:"v./adj.",zh:"放松；宽松",en:"Made less strict.",ex:"Rules were relaxed.",forms:"relax; relaxation"},
{w:"confined",sl:9,pos:"v./adj.",zh:"限制；局限",en:"Kept within limits.",ex:"The analysis was confined.",forms:"confine; confinement"},
{w:"accommodation",sl:9,pos:"n.",zh:"住宿；适应",en:"Lodging; adjustment.",ex:"The model accommodates observations.",forms:"accommodate; accommodated"},
{w:"temporary",sl:9,pos:"adj.",zh:"临时的",en:"Lasting brief time.",ex:"A temporary fix.",forms:"temporarily; temporize"},
{w:"distorted",sl:9,pos:"v.",zh:"扭曲；歪曲",en:"To misrepresent.",ex:"Reporting distorts understanding.",forms:"distort; distortion"},
{w:"passive",sl:9,pos:"adj.",zh:"被动的",en:"Not active.",ex:"Passive resistance.",forms:"passively; passivity"},
{w:"subordinate",sl:9,pos:"adj./n.",zh:"下级的；下属",en:"Lower in rank.",ex:"A subordinate role.",forms:"subordinates; subordination"},
{w:"analogous",sl:9,pos:"adj.",zh:"类似的；类比的",en:"Comparable.",ex:"The analogy holds.",forms:"analogy; analogue"},
{w:"military",sl:9,pos:"adj./n.",zh:"军事的",en:"Of armed forces.",ex:"Military spending rose.",forms:"militarily; militia"},
{w:"scenario",sl:9,pos:"n.",zh:"情景；场景",en:"A possible situation.",ex:"The worst scenario.",forms:"scenarios"},
{w:"revolution",sl:9,pos:"n.",zh:"革命；巨变",en:"A dramatic change.",ex:"The industrial revolution.",forms:"revolutions; revolutionary"},
{w:"diminished",sl:9,pos:"v.",zh:"减少；削弱",en:"To make less.",ex:"The effect diminished.",forms:"diminish; diminution"},
{w:"coherence",sl:9,pos:"n.",zh:"连贯性；一致性",en:"Logical consistency.",ex:"Narrative coherence matters.",forms:"coherent; cohesively"},
{w:"suspended",sl:9,pos:"v.",zh:"暂停；悬挂",en:"To stop temporarily.",ex:"The license was suspended.",forms:"suspend; suspension"},
{w:"mature",sl:9,pos:"v./adj.",zh:"成熟",en:"Fully developed.",ex:"Mature learners differ.",forms:"matures; maturity"},
{w:"assurance",sl:9,pos:"n.",zh:"保证；保险",en:"A pledge.",ex:"They assured participants.",forms:"assure; assured"},
{w:"rigid",sl:9,pos:"adj.",zh:"僵化的；刚性的",en:"Not flexible.",ex:"Rigid rules.",forms:"rigidly; rigidity"},
{w:"controversy",sl:9,pos:"n.",zh:"争议",en:"Public disagreement.",ex:"The study sparked controversy.",forms:"controversial; controvert"},
{w:"sphere",sl:9,pos:"n.",zh:"领域；球体",en:"A domain; a globe.",ex:"In the public sphere.",forms:"spheres; spherical"},
{w:"mediation",sl:9,pos:"n.",zh:"调解；仲裁",en:"Intervention to resolve.",ex:"Mediation settled it.",forms:"mediate; mediator"},
{w:"format",sl:9,pos:"n./v.",zh:"格式；编排",en:"Arrangement.",ex:"Follow the format.",forms:"formats; formatted"},
{w:"trigger",sl:9,pos:"n./v.",zh:"触发；引发",en:"To cause an event.",ex:"The trigger was cost.",forms:"triggers; triggered"},
{w:"qualitative",sl:9,pos:"adj.",zh:"定性的",en:"Of quality.",ex:"Qualitative data mattered.",forms:"qualitatively; quality"},
{w:"portion",sl:9,pos:"n.",zh:"部分",en:"A share.",ex:"A large portion affected.",forms:"portions; proportion"},
{w:"medium",sl:9,pos:"n./adj.",zh:"媒介；中等的",en:"A means; in between.",ex:"The medium was water.",forms:"media; medial"},
{w:"coincide",sl:9,pos:"v.",zh:"巧合；一致",en:"To occur together.",ex:"Timing coincides with literacy.",forms:"coincides; coincidence"},
{w:"violation",sl:9,pos:"n.",zh:"违反；违背",en:"A breach of rule.",ex:"A violation occurred.",forms:"violate; violated"},
{w:"device",sl:9,pos:"n.",zh:"装置；设备",en:"A tool or gadget.",ex:"The device failed.",forms:"devices; devise"},
{w:"insights",sl:9,pos:"n.",zh:"洞见；领悟",en:"Deep understanding.",ex:"They gained insights.",forms:"insight; insightful"},
{w:"refine",sl:9,pos:"v.",zh:"精炼；改进",en:"To improve.",ex:"They refined the model.",forms:"refines; refined; refinement"},
{w:"devoted",sl:9,pos:"v.",zh:"奉献；致力",en:"To give time to.",ex:"Half the budget was devoted.",forms:"devote; devotion"},
{w:"team",sl:9,pos:"n.",zh:"团队",en:"A group working.",ex:"The team succeeded.",forms:"teams; teamwork"},
{w:"overlap",sl:9,pos:"v./n.",zh:"重叠",en:"To cover partly.",ex:"The periods overlap.",forms:"overlaps; overlapped"},
{w:"attained",sl:9,pos:"v.",zh:"达到；获得",en:"To achieve.",ex:"They attained admission.",forms:"attain; attainment"},
{w:"restraints",sl:9,pos:"n.",zh:"限制；约束",en:"Things that restrain.",ex:"Restraints were lifted.",forms:"restrain; restrained"},
{w:"inherent",sl:9,pos:"adj.",zh:"固有的；内在的",en:"Existing as essential.",ex:"Inherent risks.",forms:"inherently; inherit"},
{w:"route",sl:9,pos:"n./v.",zh:"路线；途径",en:"A path.",ex:"The route was clear.",forms:"routes; routed"},
{w:"protocol",sl:9,pos:"n.",zh:"协议；规程",en:"A set procedure.",ex:"Follow the protocol.",forms:"protocols; prototypical"},
{w:"founded",sl:9,pos:"v.",zh:"建立；创立",en:"To set up.",ex:"The institute was founded in 1965.",forms:"found; foundation"},
{w:"duration",sl:9,pos:"n.",zh:"持续时间",en:"Length of time.",ex:"The duration was short.",forms:"durable; during"},
// ===== Sublist 10 (30) =====
{w:"whereby",sl:10,pos:"conj.",zh:"凭此；由此",en:"By which.",ex:"A system whereby X occurs.",forms:""},
{w:"inclination",sl:10,pos:"n.",zh:"倾向；斜坡",en:"A tendency.",ex:"An inclination to agree.",forms:"incline; inclined"},
{w:"encountered",sl:10,pos:"v.",zh:"遇到；遭遇",en:"To meet.",ex:"They encountered issues.",forms:"encounter; encounterable"},
{w:"convinced",sl:10,pos:"v./adj.",zh:"说服；确信",en:"To cause to believe.",ex:"Evidence convinced them.",forms:"convince; convincing"},
{w:"assembly",sl:10,pos:"n.",zh:"集会；装配",en:"A gathering; putting together.",ex:"They assembled evidence.",forms:"assemble; assembled"},
{w:"albeit",sl:10,pos:"conj.",zh:"虽然；尽管",en:"Although.",ex:"Encouraging, albeit preliminary.",forms:""},
{w:"enormous",sl:10,pos:"adj.",zh:"巨大的",en:"Very large.",ex:"An enormous volume of data.",forms:"enormously; enormity"},
{w:"reluctant",sl:10,pos:"adj.",zh:"不情愿的",en:"Unwilling.",ex:"Reluctant to change.",forms:"reluctantly; reluctance"},
{w:"posed",sl:10,pos:"v.",zh:"提出；造成",en:"To present.",ex:"They posed a question.",forms:"pose; posture"},
{w:"persistent",sl:10,pos:"adj.",zh:"持续的；执着的",en:"Continuing firmly.",ex:"Disparities persist.",forms:"persist; persistence"},
{w:"undergo",sl:10,pos:"v.",zh:"经历；承受",en:"To experience.",ex:"They underwent training.",forms:"undergoes; undergone; undergoing"},
{w:"notwithstanding",sl:10,pos:"prep.",zh:"尽管",en:"Despite.",ex:"Notwithstanding risks, they proceeded.",forms:""},
{w:"straightforward",sl:10,pos:"adj.",zh:"直截了当的",en:"Simple; direct.",ex:"A straightforward task.",forms:"straight; forward"},
{w:"panel",sl:10,pos:"n.",zh:"小组；面板",en:"A group of experts.",ex:"An expert panel convened.",forms:"panels; panelled"},
{w:"odd",sl:10,pos:"adj.",zh:"奇怪的；奇数的",en:"Unusual; not even.",ex:"An odd result.",forms:"odds; oddly"},
{w:"intrinsic",sl:10,pos:"adj.",zh:"内在的；本质的",en:"Belonging naturally.",ex:"Intrinsic motivation.",forms:"intrinsically; intrinsical"},
{w:"compiled",sl:10,pos:"v.",zh:"汇编；编纂",en:"To gather from sources.",ex:"The database was compiled.",forms:"compile; compilation"},
{w:"adjacent",sl:10,pos:"adj.",zh:"相邻的",en:"Next to.",ex:"Adjacent neighborhoods.",forms:"adjacently; adjacency"},
{w:"integrity",sl:10,pos:"n.",zh:"完整性；诚实",en:"Wholeness; honesty.",ex:"Academic integrity matters.",forms:"integral; integrate"},
{w:"forthcoming",sl:10,pos:"adj.",zh:"即将到来的",en:"About to appear.",ex:"Results will be forthcoming.",forms:""},
{w:"conceived",sl:10,pos:"v.",zh:"构想；设想",en:"To form an idea.",ex:"The theory was conceived in the 1940s.",forms:"conceive; conception"},
{w:"ongoing",sl:10,pos:"adj.",zh:"进行中的",en:"Continuing.",ex:"Ongoing debate.",forms:"on; going"},
{w:"so-called",sl:10,pos:"adj.",zh:"所谓的",en:"Allegedly named.",ex:"The so-called expert.",forms:"so; called"},
{w:"likewise",sl:10,pos:"adv.",zh:"同样地",en:"Similarly.",ex:"Likewise, they agreed.",forms:"like; wise"},
{w:"nonetheless",sl:10,pos:"adv.",zh:"尽管如此",en:"Nevertheless.",ex:"Costly; nonetheless needed.",forms:"none; theless"},
{w:"levy",sl:10,pos:"n./v.",zh:"征税；征收",en:"A tax; to impose.",ex:"They levied a tax.",forms:"levies; levied"},
{w:"invoked",sl:10,pos:"v.",zh:"援引；调用",en:"To call upon.",ex:"They invoked a clause.",forms:"invoke; invocation"},
{w:"colleagues",sl:10,pos:"n.",zh:"同事",en:"Co-workers.",ex:"Colleagues supported it.",forms:"colleague; collegial"},
{w:"depression",sl:10,pos:"n.",zh:"萧条；抑郁",en:"Severe downturn; sadness.",ex:"The depression deepened.",forms:"depress; depressed"},
{w:"collapse",sl:10,pos:"n./v.",zh:"崩溃；倒塌",en:"Sudden failure.",ex:"The collapse was dramatic.",forms:"collapses; collapsed; collapsible"}
];

// 浏览器中 const AWL 已是全局词法绑定，vocab.html 可直接访问；此处兼容 Node 测试。
if (typeof module !== 'undefined' && module.exports) module.exports = AWL;
